db:
  image: mongo
  restart: always

app: &app_base
  build: .
  volumes:
    - /opt/app/public
  command: node bin/www
  restart: always
  ports:
    - "3000:3000"
  links:
    - db
  env_file: .env.docker

nginx:
  build: nginx
  ports:
    - "80:80"
  links:
    - app
  volumes_from:
    - app
